name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  integration-tests-android:
    name: Android Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      JAVA_TOOL_OPTIONS: -Xms512m -Xmx2048m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2048m -Dfile.encoding=UTF-8'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: |
          flutter pub get

      # Ensure integration_test is present
      - name: Verify integration_test dependency
        run: |
          if ! grep -q "integration_test:" pubspec.yaml; then
            echo "::error::Missing dev_dependencies: integration_test"
            exit 1
          fi

      # Start Android emulator, then run integration tests on it
      - name: Run integration tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          profile: Nexus 6
          script: |
            adb devices
            flutter doctor -v
            # Build once to warm caches & fail fast on Gradle issues
            flutter build apk --debug
            # Run the integration test suite on the emulator
            flutter test integration_test/

      - name: Upload test results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-logs
          path: |
            build/*
            **/test/**/reports/**
            **/integration_test/**/reports/**
          if-no-files-found: ignore
