name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  analyze-and-lint:
    name: Analyze & Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true

      - name: Print versions
        run: |
          flutter --version
          dart --version

      - name: Get dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage --exclude-tags=integration

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: coverage/
          if-no-files-found: ignore

  widget-tests:
    name: Widget Tests
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run widget tests
        run: flutter test test/ui/ test/layout/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: widget-test-results
          path: |
            test/reports/
            test/**/reports/
          if-no-files-found: ignore

  golden-tests:
    name: Golden Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run golden tests
        run: flutter test test/goldens/

      - name: Upload golden test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: golden-test-results
          path: |
            test/goldens/
            test/goldens/failures/
          if-no-files-found: ignore

  integration-tests-android:
    name: Integration Tests (Android)
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      JAVA_TOOL_OPTIONS: -Xms512m -Xmx2048m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2048m -Dfile.encoding=UTF-8'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      # Ensure integration_test is present
      - name: Verify integration_test dependency
        run: |
          if ! grep -q "integration_test:" pubspec.yaml; then
            echo "::error::Missing dev_dependencies: integration_test"
            exit 1
          fi

      # Start Android emulator, then run integration tests on it
      - name: Run integration tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          profile: Nexus 6
          script: |
            adb devices
            flutter doctor -v
            # Build once to warm caches & fail fast on Gradle issues
            flutter build apk --debug
            # Run the integration test suite on the emulator
            flutter test integration_test/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-logs
          path: |
            build/*
            **/test/**/reports/**
            **/integration_test/**/reports/**
          if-no-files-found: ignore

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      JAVA_TOOL_OPTIONS: -Xms512m -Xmx2048m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2048m -Dfile.encoding=UTF-8'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android APK (Debug)
        run: flutter build apk --debug

      - name: Build Android APK (Release)
        run: flutter build apk --release

      - name: Build iOS (macOS runner would be needed for actual build)
        run: flutter build ios --no-codesign --debug

      - name: Build Web
        run: flutter build web

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/app/outputs/
            build/web/
          if-no-files-found: ignore

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run dependency audit
        run: flutter pub deps --json | grep -E "(name|version)" || echo "Dependencies listed"

      - name: Check for known vulnerabilities
        run: flutter pub outdated --json || echo "Outdated dependencies checked"

  performance-check:
    name: Performance Check
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run performance tests
        run: flutter test test/perf/

      - name: Check app size
        run: |
          flutter build apk --target-platform android-arm64 --analyze-size
          echo "Build size analysis completed"

      - name: Upload performance results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: |
            test/perf/reports/
            build/app/outputs/mapping/
          if-no-files-found: ignore