name: Design Fidelity

on:
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

env:
  FIDELITY_THRESHOLD: "0.95"

jobs:
  fidelity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Run design fidelity audit
        run: dart run tools/design_fidelity.dart --threshold $FIDELITY_THRESHOLD

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DESIGN_FIDELITY_REPORT
          path: docs/DESIGN_FIDELITY_REPORT.md
